# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-03 08:07
from __future__ import unicode_literals

import custom_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddPdfFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', custom_field.fields.ContextTypeRestrictedFileField(upload_to='pdf')),
            ],
        ),
        migrations.CreateModel(
            name='ListTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', custom_field.fields.ListFiled()),
            ],
        ),
    ]
