# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-30 09:05
from __future__ import unicode_literals

import custom_form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=10, validators=[custom_form.models.validate_pre])),
                ('title', models.CharField(max_length=10)),
            ],
        ),
    ]
