# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-03 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='type',
            field=models.IntegerField(choices=[(1, '唐诗'), (2, '宋词')], default=1),
        ),
    ]
