# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-30 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('merge_databases_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.AlterModelManagers(
            name='todo',
            managers=[
                ('todolist', django.db.models.manager.Manager()),
            ],
        ),
    ]
